In [24]:
import sys  
import json
import pandas as pd
import numpy as np
import lightgbm as lgb

sys.path.insert(0, '../')
import gbdt_forecast

In [25]:
params_path = '../params/params_eem2020_wind_example.json'
with open(params_path, 'r', encoding='utf-8') as file:
    params_json = json.loads(file.read())

In [26]:
params_json

{'trial_name': 'trial0',
 'trial_comment': 'test',
 'path_result': './result/eem20/',
 'path_raw_data': './data/eem20/',
 'filename_raw_data': 'eem2020-raw.csv',
 'path_preprocessed_data': './data/eem20/preprocessed/',
 'filename_preprocessed_data': 'data_final_zero_one_normalized.csv',
 'data_resolution': '60min',
 'splits': {'train': [['2000-01-01 01:00:00', '2000-10-01 00:00:00']],
  'valid': [['2000-11-01 01:00:00', '2000-12-31 00:00:00']]},
 'sites': ['SE1', 'SE2', 'SE3', 'SE4'],
 'features': ['Temperature_0',
  'RelativeHumidity_0',
  'Pressure_0',
  'CloudCover_0',
  'WindGustSpeed_0',
  'WindSpeed_0',
  'WindDirection_0'],
 'target': 'Power',
 'diff_target_with_physical': False,
 'target_smoothing_window': 1,
 'regression_params': {'type': ['quantile'],
  'alpha_range': [0.1, 1.0, 0.1],
  'quantile_postprocess': 'sorting',
  'target_min_max': [None, None]},
 'model_params': {'lightgbm': {'learning_rate': 0.1,
   'num_trees': 20,
   'boosting': 'gbdt',
   'max_leaves': 32,
   'max_depth': 10,
   'min_data_in_leaf': 20,
   'max_bin': 30,
   'bagging_fraction': 1,
   'bagging_freq': 0,
   'feature_fraction': 1,
   'early_stopping': 5,
   'lambda_l1': 0.0,
   'lambda_l2': 0.0,
   'verbose': -1,
   'num_threads': 1}},
 'weight_params': {'weight_end': 1.0, 'weight_shape': 80},
 'save_options': {'data': False,
  'prediction': True,
  'model': True,
  'evals': False,
  'loss': True,
  'overall_score': True}}

In [68]:
trial_name = 'trial0'
model = 'lightgbm'

sites = range(len(params_json['sites']))
splits = range(len(params_json['splits']['valid']))
alpha_q = np.arange(params_json['regression_params']['alpha_range'][0],
                    params_json['regression_params']['alpha_range'][1],
                    params_json['regression_params']['alpha_range'][2])

gbm_site = []
for site in sites:
    gbm_split = []
    for split in splits:
        gbm_q = {}
        for alpha in alpha_q:
            file_name = '../result/eem20/'+trial_name+'/gbm_model/gbm_model_'+model+'_q_quantile{0:.2f}_split_{1}_site_{2}.txt'.format(alpha, split, site)
            if model == 'lightgbm': 
                gbm = lgb.Booster(model_file=file_name)
            elif model == 'catboost':
                gbm = cb.CatBoostRegressor().load_model(file_name)
            gbm_q['quantile{0:.2f}'.format(alpha)] = gbm
        
        gbm_split.append(gbm_q)
    gbm_site.append(gbm_split)

In [69]:
df_X = pd.read_csv('../data/eem20/preprocessed/data_final_zero_one_normalized.csv', index_col=[0,1], header=[0,1])

In [70]:
trial = gbdt_forecast.Trial(params_json)

In [71]:
df_X

                                           SE1                                \
                                 Temperature_0 RelativeHumidity_0 Pressure_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00     270.14926           0.981022   99697.21
             2000-01-01 01:00:00     270.06406           0.980828   99654.18
             2000-01-01 02:00:00     270.04492           0.980874   99614.89
             2000-01-01 03:00:00     270.01850           0.981637   99560.07
             2000-01-01 04:00:00     270.02536           0.983668   99513.10
...                                        ...                ...        ...
2000-12-31   2000-12-31 19:00:00     267.19565           0.715043  100252.07
             2000-12-31 20:00:00     266.94232           0.711884  100453.88
             2000-12-31 21:00:00     266.61667           0.725288  100651.61
             2000-12-31 22:00:00     266.38275           0.722083  100846.75
             2000-12-31 23:00:00     266.11154           0.723454  101044.13

                                                                           \
                                 CloudCover_0 WindGustSpeed_0 WindSpeed_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00     0.999979        9.486829    4.993632
             2000-01-01 01:00:00     1.000000        9.282259    4.502751
             2000-01-01 02:00:00     1.000000        8.298201    4.256284
             2000-01-01 03:00:00     1.000000        7.815304    4.185637
             2000-01-01 04:00:00     1.000000        7.550981    3.995219
...                                       ...             ...         ...
2000-12-31   2000-12-31 19:00:00     0.847345       19.014013    8.738104
             2000-12-31 20:00:00     0.841644       19.204440    8.693635
             2000-12-31 21:00:00     0.487979       18.930569    8.499709
             2000-12-31 22:00:00     0.353604       18.418383    8.178779
             2000-12-31 23:00:00     0.304413       17.753016    7.627296

                                                           SE2  \
                                 WindDirection_0 Temperature_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00      278.587777     266.29095
             2000-01-01 01:00:00      285.627465     266.81268
             2000-01-01 02:00:00      293.956715     267.31152
             2000-01-01 03:00:00      298.041503     267.78010
             2000-01-01 04:00:00      303.615424     268.19745
...                                          ...           ...
2000-12-31   2000-12-31 19:00:00       93.895614     267.66162
             2000-12-31 20:00:00       96.327828     267.42080
             2000-12-31 21:00:00       96.315182     267.11243
             2000-12-31 22:00:00       96.320073     266.77400
             2000-12-31 23:00:00       99.055959     266.46927

                                                                ...  \
                                 RelativeHumidity_0 Pressure_0  ...
ref_datetime valid_datetime                                     ...
2000-01-01   2000-01-01 00:00:00           0.990853   99131.40  ...
             2000-01-01 01:00:00           0.989967   99030.55  ...
             2000-01-01 02:00:00           0.990838   98937.67  ...
             2000-01-01 03:00:00           0.990665   98838.88  ...
             2000-01-01 04:00:00           0.989776   98761.58  ...
...                                             ...        ...  ...
2000-12-31   2000-12-31 19:00:00           0.677650  100806.57  ...
             2000-12-31 20:00:00           0.639092  101038.80  ...
             2000-12-31 21:00:00           0.618090  101254.39  ...
             2000-12-31 22:00:00           0.623507  101451.29  ...
             2000-12-31 23:00:00           0.631230  101638.53  ...

                                                SE4                           \
                                 RelativeHumidity_9  Pressure_9 CloudCover_9
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00           0.984791   99115.890     0.991037
             2000-01-01 01:00:00           0.981240   99119.430     0.999628
             2000-01-01 02:00:00           0.979866   99116.930     0.962546
             2000-01-01 03:00:00           0.975909   99100.630     0.865341
             2000-01-01 04:00:00           0.974445   99095.086     0.903955
...                                             ...         ...          ...
2000-12-31   2000-12-31 19:00:00           0.745385   99633.630     0.174341
             2000-12-31 20:00:00           0.746739   99746.320     0.508890
             2000-12-31 21:00:00           0.731922   99877.640     0.439935
             2000-12-31 22:00:00           0.696367  100025.150     0.441336
             2000-12-31 23:00:00           0.667282  100167.880     0.494424

                                                                              \
                                 WindGustSpeed_9 WindSpeed_9 WindDirection_9
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00        5.283467    2.161229      222.845087
             2000-01-01 01:00:00        4.908387    2.341834      214.523404
             2000-01-01 02:00:00        5.174319    2.382783      218.252877
             2000-01-01 03:00:00        5.430425    2.548630      212.060967
             2000-01-01 04:00:00        5.323391    2.464750      214.875567
...                                          ...         ...             ...
2000-12-31   2000-12-31 19:00:00       12.668310    5.188400      130.755607
             2000-12-31 20:00:00       12.265768    5.437722      122.059740
             2000-12-31 21:00:00       12.747267    5.607091      119.766437
             2000-12-31 22:00:00       13.141333    5.779373      117.519477
             2000-12-31 23:00:00       13.339587    5.743985      114.296047

                                       SE1       SE2       SE3       SE4
                                     Power     Power     Power     Power
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00  0.447719  0.205508  0.349376  0.272433
             2000-01-01 01:00:00  0.429218  0.198224  0.299740  0.266137
             2000-01-01 02:00:00  0.412413  0.219203  0.269001  0.240638
             2000-01-01 03:00:00  0.394074  0.259537  0.244949  0.227775
             2000-01-01 04:00:00  0.337418  0.281938  0.217935  0.224420
...                                    ...       ...       ...       ...
2000-12-31   2000-12-31 19:00:00  0.650026  0.835303  0.850008  0.791320
             2000-12-31 20:00:00  0.648598  0.817893  0.827932  0.815762
             2000-12-31 21:00:00  0.634850  0.815446  0.812573  0.804159
             2000-12-31 22:00:00  0.630552  0.818527  0.794817  0.807252
             2000-12-31 23:00:00  0.630547  0.811302  0.782750  0.821077

[8736 rows x 284 columns]

In [77]:
df_X

                                           SE1                                \
                                 Temperature_0 RelativeHumidity_0 Pressure_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00     270.14926           0.981022   99697.21
             2000-01-01 01:00:00     270.06406           0.980828   99654.18
             2000-01-01 02:00:00     270.04492           0.980874   99614.89
             2000-01-01 03:00:00     270.01850           0.981637   99560.07
             2000-01-01 04:00:00     270.02536           0.983668   99513.10
...                                        ...                ...        ...
2000-12-31   2000-12-31 19:00:00     267.19565           0.715043  100252.07
             2000-12-31 20:00:00     266.94232           0.711884  100453.88
             2000-12-31 21:00:00     266.61667           0.725288  100651.61
             2000-12-31 22:00:00     266.38275           0.722083  100846.75
             2000-12-31 23:00:00     266.11154           0.723454  101044.13

                                                                           \
                                 CloudCover_0 WindGustSpeed_0 WindSpeed_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00     0.999979        9.486829    4.993632
             2000-01-01 01:00:00     1.000000        9.282259    4.502751
             2000-01-01 02:00:00     1.000000        8.298201    4.256284
             2000-01-01 03:00:00     1.000000        7.815304    4.185637
             2000-01-01 04:00:00     1.000000        7.550981    3.995219
...                                       ...             ...         ...
2000-12-31   2000-12-31 19:00:00     0.847345       19.014013    8.738104
             2000-12-31 20:00:00     0.841644       19.204440    8.693635
             2000-12-31 21:00:00     0.487979       18.930569    8.499709
             2000-12-31 22:00:00     0.353604       18.418383    8.178779
             2000-12-31 23:00:00     0.304413       17.753016    7.627296

                                                           SE2  \
                                 WindDirection_0 Temperature_0
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00      278.587777     266.29095
             2000-01-01 01:00:00      285.627465     266.81268
             2000-01-01 02:00:00      293.956715     267.31152
             2000-01-01 03:00:00      298.041503     267.78010
             2000-01-01 04:00:00      303.615424     268.19745
...                                          ...           ...
2000-12-31   2000-12-31 19:00:00       93.895614     267.66162
             2000-12-31 20:00:00       96.327828     267.42080
             2000-12-31 21:00:00       96.315182     267.11243
             2000-12-31 22:00:00       96.320073     266.77400
             2000-12-31 23:00:00       99.055959     266.46927

                                                                ...  \
                                 RelativeHumidity_0 Pressure_0  ...
ref_datetime valid_datetime                                     ...
2000-01-01   2000-01-01 00:00:00           0.990853   99131.40  ...
             2000-01-01 01:00:00           0.989967   99030.55  ...
             2000-01-01 02:00:00           0.990838   98937.67  ...
             2000-01-01 03:00:00           0.990665   98838.88  ...
             2000-01-01 04:00:00           0.989776   98761.58  ...
...                                             ...        ...  ...
2000-12-31   2000-12-31 19:00:00           0.677650  100806.57  ...
             2000-12-31 20:00:00           0.639092  101038.80  ...
             2000-12-31 21:00:00           0.618090  101254.39  ...
             2000-12-31 22:00:00           0.623507  101451.29  ...
             2000-12-31 23:00:00           0.631230  101638.53  ...

                                                SE4                           \
                                 RelativeHumidity_9  Pressure_9 CloudCover_9
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00           0.984791   99115.890     0.991037
             2000-01-01 01:00:00           0.981240   99119.430     0.999628
             2000-01-01 02:00:00           0.979866   99116.930     0.962546
             2000-01-01 03:00:00           0.975909   99100.630     0.865341
             2000-01-01 04:00:00           0.974445   99095.086     0.903955
...                                             ...         ...          ...
2000-12-31   2000-12-31 19:00:00           0.745385   99633.630     0.174341
             2000-12-31 20:00:00           0.746739   99746.320     0.508890
             2000-12-31 21:00:00           0.731922   99877.640     0.439935
             2000-12-31 22:00:00           0.696367  100025.150     0.441336
             2000-12-31 23:00:00           0.667282  100167.880     0.494424

                                                                              \
                                 WindGustSpeed_9 WindSpeed_9 WindDirection_9
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00        5.283467    2.161229      222.845087
             2000-01-01 01:00:00        4.908387    2.341834      214.523404
             2000-01-01 02:00:00        5.174319    2.382783      218.252877
             2000-01-01 03:00:00        5.430425    2.548630      212.060967
             2000-01-01 04:00:00        5.323391    2.464750      214.875567
...                                          ...         ...             ...
2000-12-31   2000-12-31 19:00:00       12.668310    5.188400      130.755607
             2000-12-31 20:00:00       12.265768    5.437722      122.059740
             2000-12-31 21:00:00       12.747267    5.607091      119.766437
             2000-12-31 22:00:00       13.141333    5.779373      117.519477
             2000-12-31 23:00:00       13.339587    5.743985      114.296047

                                       SE1       SE2       SE3       SE4
                                     Power     Power     Power     Power
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00  0.447719  0.205508  0.349376  0.272433
             2000-01-01 01:00:00  0.429218  0.198224  0.299740  0.266137
             2000-01-01 02:00:00  0.412413  0.219203  0.269001  0.240638
             2000-01-01 03:00:00  0.394074  0.259537  0.244949  0.227775
             2000-01-01 04:00:00  0.337418  0.281938  0.217935  0.224420
...                                    ...       ...       ...       ...
2000-12-31   2000-12-31 19:00:00  0.650026  0.835303  0.850008  0.791320
             2000-12-31 20:00:00  0.648598  0.817893  0.827932  0.815762
             2000-12-31 21:00:00  0.634850  0.815446  0.812573  0.804159
             2000-12-31 22:00:00  0.630552  0.818527  0.794817  0.807252
             2000-12-31 23:00:00  0.630547  0.811302  0.782750  0.821077

[8736 rows x 284 columns]

In [79]:
dfs_y_pred = trial.predict_model_split_site([[df_X['SE1'], df_X['SE2'], df_X['SE3'], df_X['SE4']]], {model: gbm_site})

 25%|██▌       | 1/4 [00:00<00:00,  7.55it/s]

Predicting...

In [87]:
dfs_y_pred['lightgbm'][0][0]

                                  quantile10  quantile20  quantile30  \
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00    0.226095    0.299862    0.398635
             2000-01-01 01:00:00    0.224595    0.299862    0.400803
             2000-01-01 02:00:00    0.183567    0.233735    0.308788
             2000-01-01 03:00:00    0.183567    0.233735    0.308788
             2000-01-01 04:00:00    0.153018    0.233735    0.308788
...                                      ...         ...         ...
2000-12-31   2000-12-31 19:00:00    0.276491    0.419746    0.521715
             2000-12-31 20:00:00    0.276491    0.419746    0.521715
             2000-12-31 21:00:00    0.276491    0.419746    0.521715
             2000-12-31 22:00:00    0.276491    0.419746    0.521715
             2000-12-31 23:00:00    0.276491    0.419746    0.497583

                                  quantile40  quantile50  quantile60  \
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00    0.444501    0.455626    0.458126
             2000-01-01 01:00:00    0.434786    0.440294    0.444928
             2000-01-01 02:00:00    0.324575    0.331211    0.333070
             2000-01-01 03:00:00    0.324575    0.331211    0.333070
             2000-01-01 04:00:00    0.317847    0.321932    0.331108
...                                      ...         ...         ...
2000-12-31   2000-12-31 19:00:00    0.613932    0.680765    0.730058
             2000-12-31 20:00:00    0.613932    0.680765    0.730058
             2000-12-31 21:00:00    0.613932    0.680765    0.736653
             2000-12-31 22:00:00    0.613932    0.680765    0.736653
             2000-12-31 23:00:00    0.613932    0.666888    0.723236

                                  quantile70  quantile80  quantile90
ref_datetime valid_datetime
2000-01-01   2000-01-01 00:00:00    0.502574    0.571145    0.706504
             2000-01-01 01:00:00    0.532432    0.584472    0.640881
             2000-01-01 02:00:00    0.348150    0.431088    0.556552
             2000-01-01 03:00:00    0.348150    0.431088    0.556552
             2000-01-01 04:00:00    0.353191    0.419178    0.507733
...                                      ...         ...         ...
2000-12-31   2000-12-31 19:00:00    0.733286    0.736653    0.789329
             2000-12-31 20:00:00    0.733286    0.736653    0.789329
             2000-12-31 21:00:00    0.744846    0.746080    0.774568
             2000-12-31 22:00:00    0.742476    0.744846    0.795027
             2000-12-31 23:00:00    0.736653    0.747800    0.803502

[8736 rows x 9 columns]